name: rnaseq
channels:
  - conda-forge
  - bioconda
  - r
  - nodefaults
dependencies:
  - pigz
  - python
  - pysam
  - snakemake
  - graphviz
  - salmon
  - fastqc
  - falco
  - cutadapt
  - bedtools
  - ucsc-bedgraphtobigwig
  - pandoc
  - tbb
  - samtools
  - trim-galore
  - multiqc
  - igv
  - igvtools
  - fastp
  - pandas=1.3
  - numpy=1.20
  - scipy=1.7
  - xlrd
  - openpyxl=3.0
  - r-essentials
  - r-base
  - r-tidyverse
  - r-furrr
  - r-devtools
  - r-glue
  - r-patchwork
  - r-ggsci
  - r-tinytex
  - r-curl
  - r-rsqlite
  - r-xml2
  - r-httpuv
  - r-mass
  - r-matrix
  - r-pheatmap
  - r-ggtext
  - r-ggrepel
  - r-flextable
  - r-officer
  - r-dt
  - r-ggVennDiagram
  - r-ggvenn
  - r-ashr
  - r-gprofiler2
  - r-msigdbr
  - r-ggplotify
  - r-seurat
  - r-seurat-data
  - r-azimuth
  - r-remotes
  - r-harmony
  - r-circlize
  - r-ggpubr
  - r-ggh4x
  - r-viridis
  - r-presto 
  - r-ggtangle
  - bioconductor-complexheatmap
  - bioconductor-rfastp
  - bioconductor-rsamtools
  - bioconductor-rsubread
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-biocinstaller
  - bioconductor-GenomicRanges
  - bioconductor-genefilter
  - bioconductor-GenomicAlignments
  - bioconductor-apeglm
  - bioconductor-rtracklayer
  - bioconductor-enrichplot
  - bioconductor-pathview
  - bioconductor-biomaRt
  - bioconductor-org.hs.eg.db
  - bioconductor-homo.sapiens
  - bioconductor-BSgenome.Hsapiens.UCSC.hg38
  - bioconductor-TxDb.Hsapiens.UCSC.hg38.knownGene
  - bioconductor-EnsDb.Hsapiens.v86
  - bioconductor-AnnotationHub
  - bioconductor-BUSpaRse
  - bioconductor-clusterProfiler
  - bioconductor-tximport
  - bioconductor-tximportdata
  - bioconductor-singler
  - bioconductor-celldex
  - bioconductor-scrnaseq
  - bioconductor-org.mm.eg.db
  - bioconductor-mus.musculus
  - bioconductor-BSgenome.mmusculus.UCSC.mm10
  - bioconductor-TxDb.mmusculus.ucsc.mm10.knownGene
  - bioconductor-ensdb.mmusculus.v79
  - bioconductor-glmgampoi
  - bioconductor-geoquery